module.exports = [
    { text: "Get me out of here" },
    { text: "They're just fine" },
    { text: "Anywhere but Hasborouck" },
    { text: "Life goes on, with or without you." },
    { text: "5’2 my height but my attitude 6’1" },
    { text: "Don’t Study me. You won’t Graduate!" },
    { text: "her attitude savage but her heart is gold." },
    { text: "Own what’s yours, or else others will try to." },
    { text: "Be a Warrior not a Worrier." },
    { text: "Go wild for a while." },
    { text: "Rolling with the hommies." },
    { text: "When you are downie, eat a brownie." },
    { text: "All we have is NOW." },
    { text: "We got that Friday feeling." },
    { text: "Catch flights not Feelings." },
    { text: "Disappointed but not surprised." },
    { text: "How I feel when there is no Coffee.DEPRESSO!" },
    { text: "50 % Savage. 50% Sweetness." },
    { text: "You can’t do epic shit with basic people." },
    { text: "I myself never feel that I’m sexy.If people call me cute, I am happier." },
    { text: "It is not how much we have, but how much we enjoy, that makes happiness." },
    { text: "The most important thing is to enjoy your life – to be happy – it’s all that matters." },
    { text: "Life is not a problem to be solved, but a reality to be experienced." },
    { text: "I love those who can smile in trouble, who can gather strength from distress, and grow brave by reflection.‘Tis the business of little minds to shrink, but they whose heart is firm, and whose conscience approves their conduct, will pursue their principles unto death." },
    { text: "It had long since come to my attention that people of accomplishment rarely sat back and let things happen to them.They went out and happened to things." },
    { text: "Love can be unselfish, in the sense of being benevolent and generous, without being selfless." },
    { text: "When I feel a little down, I put on my favorite high heels and dance" },
    { text: "Watch more sunsets than netflix." },
    { text: "Hey, I just met you, this is crazy." },
    { text: "At least this balloon is attracted to me!" },
    { text: "I must destroy you with hugs and kisses" },
    { text: "Stop looking for happiness in the same place you just lost it." },
    { text: "I woke up like this." },
    { text: "I decide the vibe." },
    { text: "If we could only turn back time…" },
    { text: "Keep smiling because life is a beautiful thing and there’s so much to smile about." },
    { text: "No one is you.That’s your power!" },
    { text: "Got my coffee and donut." },
    { text: "Escape the ordinary." },
    { text: "Sweeter than honey." },
    { text: "Proof that I can do selfies better than you" },
    { text: "A friend will always make you Smile, specially when you don’t want to…" },
    { text: "Life is like a balloon..If you never let go, you will not know how high can you rise." },
    { text: "Sometimes life can surprise you with a happy coincidence." },
    { text: "You can’t afford my Swag Bitch! #selfie" },
    { text: "This is to the Echos of our laughter" },
    { text: "The looks That we Share." },
    { text: "The never ending gossips.and the Sudden amazing get aways." },
    { text: "This is to our Past And This is to Our Future." },
    { text: "This is to our Friendship that will Never Fade." },
    { text: "Life isn’t perfect..But my Hair is! #selfieaddict" },
    { text: "Always classy, never trashy, and a little bit sassy." },
    { text: "Friday, my second favorite F word" },
    { text: "Life isn’t perfect..But my Hair is! #selfieaddict" },
    { text: "I didn’t choose the thug life, the thug life chose me." },
    { text: "When i was Rome.. I did what the Romans did." },
    { text: "I got back with my Ex…Box 360" },
    { text: "Lost in the world that doesn’t exist." },
    { text: "Today I will be as useless as letter g in lasagna." },
    { text: "You only drink diet soda? You must be so healthy." },
    { text: "The worst time to have a heart attack is during a game of charades." },
    { text: "The moment when she says you’re cute." },
    { text: "If we could only turn back time…" }
];